extern crate alloc;
#[cfg(not(target_os = "none"))]
extern crate std;

mod ascription;
mod assignment_apply;
mod binding_rules;
mod block_check;
mod call_binding_lookup;
mod call_reduction;
mod call_resolution;
mod constructor_apply;
mod context;
mod control_apply;
mod copy_capability;
mod diagnostics;
mod driver;
mod driver_entry;
mod effect_check;
mod env;
mod field_access;
mod field_apply;
mod function_apply;
mod function_check;
mod hir_finalize;
mod indirect_apply;
mod match_check;
mod model;
mod name_lookup;
mod overload_selection;
mod prefix_check;
mod selected_call_apply;
mod signature;
mod syntax_helpers;
mod trait_bound_apply;
mod trait_call_apply;
mod trait_check;
mod traits;
mod type_expr;
use context::BlockChecker;
use function_check::check_function;
use model::{AssignKind, FieldAccessorKind, FieldIdx, ScalarMatchKind, StackEntry};
use traits::BoundEnv;

pub use driver::{typecheck, TypeCheckResult};
