[build]
target = "web/index.html"
public_url = "/NEPLg2/"
release = true

[watch]
ignore = ["web/dist_ts"]

[[hooks]]
stage = "pre_build"
command = "npm.cmd"
command_arguments = ["--prefix", "web", "run", "build:ts"]
