[package]
name = "nepl-core"
version = "0.1.0"
edition = "2021"
authors = ["NEPL Team"]

[dependencies]
wasm-encoder = { version = "0.244.0", default-features = false }
wasmparser = { version = "0.244", default-features = false, features = ["validate"] }
serde.workspace = true
postcard.workspace = true

[dev-dependencies]
wasmi.workspace = true
tempfile.workspace = true
rand.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.17", features = ["js"] }
