[package]
name = "nepl-cli"
version = "0.1.0"
edition = "2021"
authors = ["NEPL Team"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
nepl-core = { path = "../nepl-core" }
nepl-gui-native = { path = "../nepl-gui-native" }
wasmi.workspace = true
wasmprinter.workspace = true
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true
wat = "=1.244.0"
