#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResourceCoveragePlaceOperation {
    ReturnValue,
    FunctionValueOutput,
    CallOutput,
    CallArgument,
    IndirectCallOutput,
    IndirectCallCallee,
    IndirectCallArgument,
    RawMemoryOutput,
    RawMemoryArgument,
    BranchOutput,
    BranchCondition,
    BranchThenValue,
    BranchElseValue,
    LoopCondition,
    MatchOutput,
    MatchScrutinee,
    MatchBindLocal,
    MatchArmValue,
    ExprOutput,
    DeclarePlace,
    DeclareInitializer,
    ReadSource,
    ReadOutput,
    MoveSource,
    MoveOutput,
    AssignTarget,
    AssignValue,
    BorrowSource,
    BorrowOutput,
    DropPlace,
    ConstructOutput,
    ConstructInput,
    RawAddressAliasSource,
    RawAddressAliasTarget,
    RawAddressViewSource,
    RawAddressViewTarget,
    StorageOriginTarget,
}

impl ResourceCoveragePlaceOperation {
    pub fn as_str(self) -> &'static str {
        match self {
            ResourceCoveragePlaceOperation::ReturnValue => "return.value",
            ResourceCoveragePlaceOperation::FunctionValueOutput => "function_value.output",
            ResourceCoveragePlaceOperation::CallOutput => "call.output",
            ResourceCoveragePlaceOperation::CallArgument => "call.arg",
            ResourceCoveragePlaceOperation::IndirectCallOutput => "indirect_call.output",
            ResourceCoveragePlaceOperation::IndirectCallCallee => "indirect_call.callee",
            ResourceCoveragePlaceOperation::IndirectCallArgument => "indirect_call.arg",
            ResourceCoveragePlaceOperation::RawMemoryOutput => "raw_memory.output",
            ResourceCoveragePlaceOperation::RawMemoryArgument => "raw_memory.arg",
            ResourceCoveragePlaceOperation::BranchOutput => "branch.output",
            ResourceCoveragePlaceOperation::BranchCondition => "branch.condition",
            ResourceCoveragePlaceOperation::BranchThenValue => "branch.then_value",
            ResourceCoveragePlaceOperation::BranchElseValue => "branch.else_value",
            ResourceCoveragePlaceOperation::LoopCondition => "loop.condition",
            ResourceCoveragePlaceOperation::MatchOutput => "match.output",
            ResourceCoveragePlaceOperation::MatchScrutinee => "match.scrutinee",
            ResourceCoveragePlaceOperation::MatchBindLocal => "match.bind_local",
            ResourceCoveragePlaceOperation::MatchArmValue => "match.arm_value",
            ResourceCoveragePlaceOperation::ExprOutput => "expr.output",
            ResourceCoveragePlaceOperation::DeclarePlace => "declare.place",
            ResourceCoveragePlaceOperation::DeclareInitializer => "declare.initializer",
            ResourceCoveragePlaceOperation::ReadSource => "read.source",
            ResourceCoveragePlaceOperation::ReadOutput => "read.output",
            ResourceCoveragePlaceOperation::MoveSource => "move.source",
            ResourceCoveragePlaceOperation::MoveOutput => "move.output",
            ResourceCoveragePlaceOperation::AssignTarget => "assign.target",
            ResourceCoveragePlaceOperation::AssignValue => "assign.value",
            ResourceCoveragePlaceOperation::BorrowSource => "borrow.source",
            ResourceCoveragePlaceOperation::BorrowOutput => "borrow.output",
            ResourceCoveragePlaceOperation::DropPlace => "drop.place",
            ResourceCoveragePlaceOperation::ConstructOutput => "construct.output",
            ResourceCoveragePlaceOperation::ConstructInput => "construct.input",
            ResourceCoveragePlaceOperation::RawAddressAliasSource => "raw_address_alias.source",
            ResourceCoveragePlaceOperation::RawAddressAliasTarget => "raw_address_alias.target",
            ResourceCoveragePlaceOperation::RawAddressViewSource => "raw_address_view.source",
            ResourceCoveragePlaceOperation::RawAddressViewTarget => "raw_address_view.target",
            ResourceCoveragePlaceOperation::StorageOriginTarget => "storage_origin.target",
        }
    }
}
